# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches: 
    - master

jobs:
  test:
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          go: [ '1.20' ]
          os: [ ubuntu-latest, macOS-latest, windows-latest ]
      name: ${{ matrix.os }} Go ${{ matrix.go }} Tests
      steps:
        - uses: actions/checkout@v3
        - name: Setup go
          uses: actions/setup-go@v3
          with:
            go-version: ${{ matrix.go }}
        - run: go mod tidy -v
        - name: Test
          run: |
            cd tests
            go test -v
        - name: Upload coverage reports to Codecov
          uses: codecov/codecov-action@v3
